# Generated by Django 4.1.7 on 2023-06-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_idultrafinedust_odultrafinedust"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idfinedust",
            name="place",
        ),
    ]
