# Generated by Django 4.1.7 on 2023-06-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_emotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeechResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
            ],
        ),
    ]
